
export const QUESTIONS = {
  "1": "What is the name of your campground?", 
  "2": "Where is your campground located? What is the address?", 
  "3": "What 'are' you? RV Park/Campground/Both?", 
  "4": "What is your campground's phone number and email Address?", 
  "5": "What is the seasonality of your campground (if any)?", 
  "6": "How many sites does your campground have?", 
  "7": "How many employees does your campground have? Tell us about them.", 
  "8": "Provide your written directions on how to reach your campground. If you do not have any, please write them here now.", 
  "9": "Is your campground friendly to all ages and group sizes? If not, what kind of crowd is it aimed towards?", 
  "10": "Is your campground pet friendly?", 
  "11": "Is your campground on/active on any social media sites? If yes, please provide the links.", 
  "12": "If you could quickly sum up why a member of our team would want to stay at your campground while they're in an elevator with you (and they're getting off soon), what would you say?", 
  "13": "Who are the owners? Tell us about them.", 
  "14": "What inspired you/the owners to start your campground business?", 
  "15": "What was the process of starting the campground like?", 
  "16": "Where are you today with your campground?", 
  "17": "Every experience becomes a story to tell in the future. What story do you want your guests to share with friends/family after staying at your campground?", 
  "18": "Tell us about your property in your own words.", 
  "19": "How large is your property? (acres)", 
  "20": "What is around your property? Be as specific as possible.", 
  "21": "What kind of vegetation grows in and around your property?", 
  "22": "What kind of animals live in and around your property?", 
  "23": "What's the weather like in and around your property?", 
  "24": "Anything else you would like to add about your property that would be of interest to a guest who is trying to decide whether to stay at your campground or your nearest competitor?", 
  "25": "What are things guests can do in and around your property? List them off.",
  "26": "For each thing you listed off, tell us about it in detail.",
  "27": "Anything else you would like to add about things to do in and around your property that would be of interest to a guest who is trying to decide whether to stay at your campground or your nearest competitor?",
  "28": "What are the amenities in your campground? List them off.",
  "29": "For each amenity you listed off, tell us about it in detail.",
  "30": "If you haven't already written about it, tell us about the: - Internet at your property - Bathrooms at your property - Water at your property and at your sites - Power at your property and at your sites - Campfires at your property and at your sites (if allowed at all)",
  "31": "Anything else you would like to add about your amenities that would be of interest to a guest who is trying to decide whether to stay at your campground or your nearest competitor?",
  "32": "Tell us about the rates for sites in your campground.",
  "33": "Do you know if your rates are competitive?",
  "34": "Do you, on your current website or elsewhere, have a FAQ that guests can look at?",
  "35": "Do you, on your current website or elsewhere, have a list of your campground rules?",
  "36": "Do you offer any free services?",
  "37": "What do you hear most often from your guests in terms of positive experiences/satisfaction?",
  "38": "Are there any guest complaints you've heard that stick out to you?",
  "39": "Do you have any guest reviews that we can't find through Google or the internet? Can you share those here?",
  "40": "Please provide us with an image of your logo.",
  "41": "We will make the color scheme of your Premium Website match the colors on your current logo. Are you okay with this?",
  "42": "Anything else you would like to add that you feel we have missed in this questionnaire?"
};
